# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Mulitple triggers
on: [ push, workflow_dispatch ]
jobs:
  say_something_else:
    needs: say_something
    runs-on: ubuntu-latest
    steps:
    - name: Something else
      run: echo "Must run after say_something"
  say_something:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is the first step"
      - name: Step 2
        run: echo "This is the second step"
